### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
as discussed in #13 – and here are some hints to it:

* my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) with the metadata structure, so you can build upon it and add other elements – such as a featureGraphic, or per-release changelogs
* my [formatting hints](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) for the `full_description.txt` should you need to update the description, or want to provide one for other languages.

Enjoy!

### CODE REVIEW

**Comment by IzzySoft** [comment]
Thanks! If you need [a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to [your app in my repo](https://apt.izzysoft.de/fdroid/index/apk/io.alexrintt.kanade), be welcome to take your pick :smiley:

**Comment by alexrintt** [comment]
Thanks! I added to the repo readme. And I'll improve the fastlane docs even more later on this week, really thanks for your pr!

I've only a doubt about the permission section, I didn't find any info in your repo about: how do you define the permissions required by an app?
image

Screenshot from [apt.izzysoft.de/fdroid/index/apk/io.alexrintt.kanade](https://apt.izzysoft.de/fdroid/index/apk/io.alexrintt.kanade).

Those versions (v0.2.1 and v0.3.0) it has only `QUERY_ALL_PACKAGES` permission.

So maybe it was queried from the past versions? (v0.1.0) when these permissions were still required?

**Comment by IzzySoft** [comment]
> I added to the repo readme

Cool, thanks!

> how do you define the permissions required by an app?

I do not *define* permissions. Fdroid reads those from the APKs (Manifest IIRC). To compare, here's the output of `aapt d badging`:

```yaml
package: name='io.alexrintt.kanade' versionCode='3' versionName='0.3.0' platformBuildVersionName='12' platformBuildVersionCode='31' compileSdkVersion='31' compileSdkVersionCodename='12' sdkVersion:'19' targetSdkVersion:'30'
uses-permission: name='android.permission.QUERY_ALL_PACKAGES'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
…
```

Obviously some dependency drags in the other two (yes, I saw your original Manifest only has the first). If you'd ask me to guess, I'd pick `shared_storage` from your `pubspec.yaml`. [Good guess](https://github.com/alexrintt/shared-storage/blob/master/android/src/main/AndroidManifest.xml) for number 2, huh?

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" package="io.alexrintt.sharedstorage">
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
</manifest>
```

I have another good guess whom you could ask on that plugin :see_no_evil: But that still doesn't tell us where `WRITE` comes from. Except if you included [your example](https://github.com/alexrintt/shared-storage/blob/b11fc2e1c91643eba3919eb54a45076571172878/example/android/app/src/main/AndroidManifest.xml) as well that is:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="io.alexrintt.sharedstorage.example">
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <application android:icon="@mipmap/ic_launcher" android:label="Shared Storage Example">
```

:man_shrugging:

**Comment by alexrintt** [comment]
I'm really confuse after debugging these apks. As you said it is probably coming from the third-party dependencies, so I removed all permissions from the shared storage example and the shared storage plugin itself, and then I compiled again... and it still prints WRITE and EXTERNAL permissions storage! lol. I'm using apktool to decompile the apk `apktool d shared-storage-example-without-any-permissions-declared.apk`:

```xml
<!-- Final apk AndroidManifest.xml -->
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

I even tried to find some subplugin/subpackages in the dependency tree that uses these permissions but I didn't find any (because the only dependency is shared storage itself and another dart based package which doesn't even has native android code).

I'll investigate further tomorrow, find some answer, cause SAF is not intended to be something I would require permissions (at least in my head from what I understood, but probably I understood wrong).

But thanks for your explanation, it helped a lot!

**Comment by IzzySoft** [comment]
That's really strange. Good luck then finding the culprit!

**Comment by alexrintt** [comment]
Ok. I found: https://github.com/anggrayudi/SimpleStorage/blob/master/storage/src/main/AndroidManifest.xml. It's a native Android library used by shared_storage plugin. I completely forget about it, lol. Thanks man.

**Comment by IzzySoft** [comment]
Glad the riddle solved!

**Pull request merged**
